# Generated by Django 4.1.7 on 2023-04-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingDate', models.DateTimeField(auto_now_add=True)),
                ('booking_name', models.CharField(max_length=30)),
                ('booking_time', models.DateTimeField(auto_now=True)),
                ('booking_phone', models.CharField(max_length=13)),
                ('person', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2)),
                ('booking_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
