# Generated by Django 4.1.7 on 2023-04-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablebooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='bookingDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='booking_time',
            field=models.DateTimeField(),
        ),
    ]
