# Generated by Django 4.1.7 on 2023-04-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablebooking', '0002_alter_tablebooking_bookingdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='booking_time',
            field=models.CharField(choices=[('10:00', '10:00')], max_length=30),
        ),
    ]
