# Generated by Django 4.1.7 on 2023-04-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablebooking', '0003_alter_tablebooking_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='bookingDate',
            field=models.CharField(max_length=200),
        ),
    ]
