# Generated by Django 4.1.7 on 2023-05-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablebooking', '0004_alter_tablebooking_bookingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='booking_phone',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='booking_time',
            field=models.CharField(choices=[('10:00 am', '10:00 am'), ('10:30 am', '10:30 am'), ('11:00 am', '11:00 am'), ('11:45 am', '11:45 am'), ('12:30 pm', '12:30 pm'), ('1:30 pm', '1:30 pm'), ('2:30 pm', '2:30 pm'), ('3:00 pm', '3:00 pm')], max_length=30),
        ),
    ]
