# Generated by Django 4.1.7 on 2023-05-01 06:08

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tablebooking', '0005_alter_tablebooking_booking_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='booking_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=10, region=None),
        ),
    ]
