# Generated by Django 4.1.7 on 2023-05-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablebooking', '0006_alter_tablebooking_booking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='booking_phone',
            field=models.IntegerField(max_length=12),
        ),
    ]
