# Generated by Django 4.1.7 on 2023-05-01 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablebooking', '0007_alter_tablebooking_booking_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablebooking',
            name='booking_phone',
        ),
    ]
