# Generated by Django 4.1.7 on 2023-04-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0002_checkout_price_checkout_qty_checkout_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='code',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
